project:
  type: book

book:
  title: "The sad story of mark FY3210"
  author: Daniel Moul
  date: "February 27, 2024"
  page-footer: 
    center: "Copyright 2024 by [Daniel Moul](https://dmoul.github.io). License: [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"
    background: dark
  # cover-image: "./images/FZ2090.jpg"
  # cover-image-alt: "Survey mark placed in Raleigh North Carolina in 1971"
  chapters:
    - "index.qmd"
    - "introducing-mark-FY3210.qmd"
    - "in-context.qmd"
    - "placement-and-recovery.qmd"
    - "mysteries.qmd"
    - "gravity-elevation.qmd"
    # n- "geology-map.qmd"
    - "facts-pointers.qmd"

#bibliography: references.bib

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    theme: cosmo
    code-fold: true
    number-sections: true
    code-summary: "Show the code"
    page-layout: full
    toc: true
    toc-depth: 3
    title-block-banner: true
